---
title: "WI Covid-19 Stats"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r process, echo=FALSE, message=FALSE, warning=FALSE}
source("WI_COVID_DATA_PROCESS.R")
```


This document contains confirmed Covid-19 cases as of `r format(MAX_DATE, format = "%A %B %d, %Y")`.

# {.tabset}

## Positive Cases by Region 
[See WI DHS for Region Definitions](https://www.dhs.wisconsin.gov/aboutdhs/regions.htm)

```{r NEW_AVG_REGION, echo=FALSE, warning=FALSE}

REGION_AVG_VALUES_POSITIVE <- ggplot(REGION_VALUES, aes(x = Date, y = AVG_7_CHANGE_POS))
REGION_AVG_VALUES_POSITIVE + geom_line(aes(color = REGION, group = REGION)) + labs(y = "", title  = "New  Covid-19 Cases (7-day trailing average)")
```


&nbsp;

```{r NEW_TOTAL_REGION, echo=FALSE, warning=FALSE}

REGION_NEW_VALUES_POSITIVE <- ggplot(REGION_VALUES, aes(fill = REGION, x = Date, y = CHANGE_POS))
REGION_NEW_VALUES_POSITIVE + geom_bar(position = "stack", stat = "identity") + labs(y = "", title  = "New Daily Covid-19 Cases")
```


&nbsp;



```{r REGION_TOTAL, echo=FALSE, warning=FALSE}


REGION_VALUES_POSITIVE <- ggplot(REGION_VALUES, aes(Date, POSITIVE))
REGION_VALUES_POSITIVE + geom_line(aes(color = REGION, group = REGION)) + scale_y_log10() + labs(y = "", title  = "Total Covid-19 Cases (Log Scale)")
```


&nbsp;


```{r REGION_PER, echo=FALSE, warning=FALSE}
REGION_POSITIVE_PER_THOUS <- ggplot(REGION_VALUES, aes(Date, REGION_POSITIVE_PER_THOUS))

REGION_POSITIVE_PER_THOUS + geom_line(aes(color = REGION, group = REGION)) +  labs(y = "", title = "Total Covid-19 Cases per 1000 People")
```



&nbsp;


```{r REGION_PERCENT, echo=FALSE, warning=FALSE}
REGION_PERCENT_POSITIVE <- ggplot(REGION_VALUES, aes(Date, AVG_7_PERCENT_POS))
REGION_PERCENT_POSITIVE + geom_line(aes(color = REGION, group = REGION)) + labs(y = "", title = "Prop. Positive Tests (7-day trailing average)") + ylim(0,.25)

```



&nbsp;



## Positive Cases in 6 Most Populous Counties


```{r NEW_AVG_COUNTY, echo=FALSE, warning=FALSE}

COUNTY_AVG_VALUES_POSITIVE <- ggplot(COUNTY_VALUES_TOP_6_COUNTIES, aes(x = Date, y = AVG_7_CHANGE_POS))
COUNTY_AVG_VALUES_POSITIVE + geom_line(aes(color = COUNTY, group = COUNTY)) + labs(y = "", title  = "New  Covid-19 Cases (7-day trailing average)")
```




```{r Largest_Counties_TOTAL, echo=FALSE, warning=FALSE}


TOP_6_COUNTIES_POSITIVE <- ggplot(COUNTY_VALUES_TOP_6_COUNTIES, aes(Date, POSITIVE))
TOP_6_COUNTIES_POSITIVE + geom_line(aes(color = COUNTY, group = COUNTY)) + scale_y_log10() + labs(y = "", title  = "Total Covid-19 Cases (Log Scale)")
```


&nbsp;


```{r Largest_Counties_PER, echo=FALSE, warning=FALSE}
TOP_6_COUNTIES_POSITIVE_PER_THOUS <- ggplot(COUNTY_VALUES_TOP_6_COUNTIES, aes(Date, COUNTY_POSITIVE_PER_THOUS))

TOP_6_COUNTIES_POSITIVE_PER_THOUS + geom_line(aes(color = COUNTY, group = COUNTY)) +  labs(y = "", title = "Total Covid-19 Cases per 1000 People")
```

&nbsp;


```{r Largest_Counties_PERCENT, echo=FALSE, warning=FALSE}
TOP_6_COUNTIES_PERCENT_POSITIVE <- ggplot(COUNTY_VALUES_TOP_6_COUNTIES, aes(Date, AVG_7_PERCENT_POS))
TOP_6_COUNTIES_PERCENT_POSITIVE + geom_line(aes(color = COUNTY, group = COUNTY)) + labs(y = "", title = "Prop. Positive Tests (7-day trailing average)") + ylim(0,.30)

```


## Positive Cases in Dane County

```{r NEW_TOTAL_DANE, echo=FALSE, warning=FALSE}

DANE_NEW_VALUES_POSITIVE <- ggplot(COUNTY_VALUES_DANE, aes(Date))
DANE_NEW_VALUES_POSITIVE  + geom_line(aes(y = AVG_7_CHANGE_POS), color = "black") + geom_line(aes(y = CHANGE_POS), color = "red") + labs(y = "", title  = "New Daily Covid-19 Cases in Dane County (7-day AVG)") 
```



# {-}
By Michael J Zenz
&nbsp;
mail (at) mjzenz (dot) org
&nbsp;
[mjzenz.org](https://www.mjzenz.org)
&nbsp;
[github](https://github.com/mjzenz/WI-Covid)
&nbsp;
`r Sys.time()`


